### ISSUE TITLE
european timezone not found or windows language != EN

### ISSUE THREAD

**Issue by Crypto-Joker** [drksheer/Crypto-PNL-Tracker#1]
Exeption of  "FindSystemTimeZoneById" wih 1 argument:  "Die Zeitzonen-ID "Mitteleuropäische Zeit"
was not found on your computer."
In C:\portable\Crypto-PNL-Tracker-main\crypto-pnl-tracker-v1.0\db-files\get-accountData.ps1:33 Zeichen:5
+     $TZ = [System.TimeZoneInfo]::FindSystemTimeZoneById($strCurrentTi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : TimeZoneNotFoundException

**Comment by drksheer** [comment]
Fixed
