### ISSUE TITLE
Errors when starting 

### ISSUE THREAD

**Issue by iller75** [drksheer/Crypto-PNL-Tracker#6]
I get this error when i start
![bild](https://user-images.githubusercontent.com/10998221/116821360-e36e9600-ab79-11eb-95e5-d998b5bd45b1.png)

I also use Daisys importer and I do have errors there too so I'm sort of suspecting it's coming from there? 

![bild](https://user-images.githubusercontent.com/10998221/116821377-fb461a00-ab79-11eb-9439-437bc724b681.png)

**Comment by Oseriduun** [comment]
you have an issue with your system time, if you look through the WH discord server, you will find a tool to fix the timestamp and then you will not have the issue from daisy's accountData script.  after that has been fixed, the error with pnl tracker should vanish as it will have data to look at. (provided you setup the account data script correctly).

**Comment by iller75** [comment]
I'm an idiot ;D Missed saving the file yesterday evening so the account names weren't correct...
