### ISSUE TITLE
Not sure what's wrong, Bybit info not correct

### ISSUE THREAD

**Issue by iller75** [drksheer/Crypto-PNL-Tracker#7]
So gotten it to run and also forward it to my other local computer so I can watch it on my main screen which I love. 
But my finance info is looking weird. Any ideas?

![bild](https://user-images.githubusercontent.com/10998221/117354828-1b474780-aeb2-11eb-9511-7b8b6e444e1c.png)

**Comment by Oseriduun** [comment]
update to 1.41 and it will show as btc/eth/eos/xrp instead of usdt (currently in pre-release though, so there may be other bugs)

**Comment by goneale** [comment]
@iller75 Please try this advice from @Oseriduun and reopen if you still have an issue.

**Comment by drksheer** [comment]
@iller75 Please try this advice from @Oseriduun and reopen if you still have an issue.
